name: docs

on:
  push:
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create doc directory if it doesn't exist
        shell: bash
        run: mkdir -p doc
      - uses: actions/checkout@v4
      - name: Generating docs with panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: pretty-ts-errors.nvim
          version: "Neovim >= 0.9.0"
          demojify: true
          treesitter: true
      - name: Update documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            docs: update `doc/pretty-ts-errors.txt`
            skip-checks: true
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add doc/
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
