name: test

on:
  pull_request:
    branches:
      - main
    paths:
      - "lua/**"
      - "tests/**"

jobs:
  run_tests:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rev: [nightly, v0.9.0, stable]

    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        name: Set up Neovim
        with:
          neovim: true
          version: ${{ matrix.rev }}

      - name: Run tests with Neovim
        shell: bash
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test
